backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: https://elgafary-gaming.netlify.app
logo_url: /images/EG_logo.png

collections:
  - name: "posts"
    label: "ğŸ“ Ø§Ù„Ø´Ø±ÙˆØ­Ø§Øª"
    files:
      - name: "posts_json"
        label: "Posts JSON"
        file: "content/posts.json"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Ø§Ù„Ø¹Ù†ÙˆØ§Ù†", name: "title", widget: "string" }
              - { label: "Ø§Ù„ÙˆØµÙ", name: "description", widget: "text" }
              - { label: "Ø§Ù„ØµÙˆØ±Ø©", name: "image", widget: "image" }
              - { label: "Ø§Ù„Ø±Ø§Ø¨Ø·", name: "link", widget: "string" }
              - { label: "Ù…Ù…ÙŠØ²", name: "featured", widget: "boolean", default: false }
              - { label: "Ø¨Ø§Ø¯Ø¬", name: "badge", widget: "string", required: false }
